# Generated by Django 5.1.1 on 2024-09-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
