# Generated by Django 5.1.1 on 2024-09-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_remove_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
