# Generated by Django 5.1.1 on 2024-09-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_complaint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='bank_card',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
